// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eojHsTxh2CznYQUhCcvLfa
// Component: ORO4GmIzqHEm
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  get as $stateGet,
  hasVariant,
  renderPlasmicSlot,
  set as $stateSet,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: eojHsTxh2CznYQUhCcvLfa/projectcss
import sty from "./PlasmicCustomSelector.module.css"; // plasmic-import: ORO4GmIzqHEm/css
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: dJv2GNb2Pwje/icon

createPlasmicElementProxy;

export const PlasmicCustomSelector__VariantProps = new Array("openSelectbar");

export const PlasmicCustomSelector__ArgProps = new Array(
  "optionsLoop",
  "selectLogo2",
  "selectLogo3"
);

const $$ = {};

function PlasmicCustomSelector__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "openSelectbar",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.openSelectbar
      },
      {
        path: "selectValue",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $props.optionsLoop[0];
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return "";
              }
              throw e;
            }
          })()
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  return (
    <div
      data-plasmic-name={"select"}
      data-plasmic-override={overrides.select}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.select,
        {
          [sty.selectopenSelectbar]: hasVariant(
            $state,
            "openSelectbar",
            "openSelectbar"
          )
        }
      )}
    >
      <div
        data-plasmic-name={"selectDropdown"}
        data-plasmic-override={overrides.selectDropdown}
        className={classNames(projectcss.all, sty.selectDropdown, {
          [sty.selectDropdownopenSelectbar]: hasVariant(
            $state,
            "openSelectbar",
            "openSelectbar"
          )
        })}
        onBlur={async event => {
          const $steps = {};
          $steps["updateOpenSelectbar"] = true
            ? (() => {
                const actionArgs = { vgroup: "openSelectbar", operation: 6 };
                return (({ vgroup, value }) => {
                  if (typeof value === "string") {
                    value = [value];
                  }
                  $stateSet($state, vgroup, false);
                  return false;
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["updateOpenSelectbar"] != null &&
            typeof $steps["updateOpenSelectbar"] === "object" &&
            typeof $steps["updateOpenSelectbar"].then === "function"
          ) {
            $steps["updateOpenSelectbar"] = await $steps["updateOpenSelectbar"];
          }
        }}
        onClick={async event => {
          const $steps = {};
          $steps["updateOpenSelectbar"] = true
            ? (() => {
                const actionArgs = { vgroup: "openSelectbar", operation: 2 };
                return (({ vgroup, value }) => {
                  if (typeof value === "string") {
                    value = [value];
                  }
                  const oldValue = $stateGet($state, vgroup);
                  $stateSet($state, vgroup, !oldValue);
                  return !oldValue;
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["updateOpenSelectbar"] != null &&
            typeof $steps["updateOpenSelectbar"] === "object" &&
            typeof $steps["updateOpenSelectbar"].then === "function"
          ) {
            $steps["updateOpenSelectbar"] = await $steps["updateOpenSelectbar"];
          }
        }}
        tabIndex={0}
      >
        <div
          data-plasmic-name={"dropdownContent"}
          data-plasmic-override={overrides.dropdownContent}
          className={classNames(projectcss.all, sty.dropdownContent, {
            [sty.dropdownContentopenSelectbar]: hasVariant(
              $state,
              "openSelectbar",
              "openSelectbar"
            )
          })}
        >
          <div
            data-plasmic-name={"dropdownLogo"}
            data-plasmic-override={overrides.dropdownLogo}
            className={classNames(projectcss.all, sty.dropdownLogo, {
              [sty.dropdownLogoopenSelectbar]: hasVariant(
                $state,
                "openSelectbar",
                "openSelectbar"
              )
            })}
          >
            {renderPlasmicSlot({
              defaultContents: (
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___23JfP)}
                  displayHeight={"24px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"24px"}
                  loading={"lazy"}
                />
              ),

              value: args.selectLogo2
            })}
          </div>
          <div
            data-plasmic-name={"dropdownLabel"}
            data-plasmic-override={overrides.dropdownLabel}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.dropdownLabel,
              {
                [sty.dropdownLabelopenSelectbar]: hasVariant(
                  $state,
                  "openSelectbar",
                  "openSelectbar"
                )
              }
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $state.selectValue;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
          {(() => {
            try {
              return true;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <Icon5Icon
              data-plasmic-name={"dropDownArrow"}
              data-plasmic-override={overrides.dropDownArrow}
              className={classNames(projectcss.all, sty.dropDownArrow, {
                [sty.dropDownArrowopenSelectbar]: hasVariant(
                  $state,
                  "openSelectbar",
                  "openSelectbar"
                )
              })}
              role={"img"}
            />
          ) : null}
        </div>
      </div>
      <div
        data-plasmic-name={"optionsUl"}
        data-plasmic-override={overrides.optionsUl}
        className={classNames(
          projectcss.all,
          sty.optionsUl,
          "select-version-scroller",
          {
            [sty.optionsUlopenSelectbar]: hasVariant(
              $state,
              "openSelectbar",
              "openSelectbar"
            )
          }
        )}
      >
        {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
          (() => {
            try {
              return $props.optionsLoop;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()
        ).map((__plasmic_item_0, __plasmic_idx_0) => {
          const currentItem = __plasmic_item_0;
          const currentIndex = __plasmic_idx_0;
          return (
            <Stack__
              as={"div"}
              data-plasmic-name={"optionLi"}
              data-plasmic-override={overrides.optionLi}
              hasGap={true}
              className={classNames(projectcss.all, sty.optionLi, {
                [sty.optionLiopenSelectbar]: hasVariant(
                  $state,
                  "openSelectbar",
                  "openSelectbar"
                )
              })}
              key={currentIndex}
              onClick={async event => {
                const $steps = {};
                $steps["updateSelectValue"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: {
                          objRoot: $state,
                          variablePath: ["selectValue"]
                        },
                        operation: 0,
                        value: currentItem
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;
                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateSelectValue"] != null &&
                  typeof $steps["updateSelectValue"] === "object" &&
                  typeof $steps["updateSelectValue"].then === "function"
                ) {
                  $steps["updateSelectValue"] = await $steps[
                    "updateSelectValue"
                  ];
                }
                $steps["updateOpenSelectbar"] = true
                  ? (() => {
                      const actionArgs = {
                        vgroup: "openSelectbar",
                        operation: 6,
                        value: "openSelectbar"
                      };
                      return (({ vgroup, value }) => {
                        if (typeof value === "string") {
                          value = [value];
                        }
                        $stateSet($state, vgroup, false);
                        return false;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateOpenSelectbar"] != null &&
                  typeof $steps["updateOpenSelectbar"] === "object" &&
                  typeof $steps["updateOpenSelectbar"].then === "function"
                ) {
                  $steps["updateOpenSelectbar"] = await $steps[
                    "updateOpenSelectbar"
                  ];
                }
              }}
            >
              <div
                data-plasmic-name={"dropdownContent2"}
                data-plasmic-override={overrides.dropdownContent2}
                className={classNames(projectcss.all, sty.dropdownContent2, {
                  [sty.dropdownContent2openSelectbar]: hasVariant(
                    $state,
                    "openSelectbar",
                    "openSelectbar"
                  )
                })}
              >
                <div
                  data-plasmic-name={"dropdownLogo2"}
                  data-plasmic-override={overrides.dropdownLogo2}
                  className={classNames(projectcss.all, sty.dropdownLogo2, {
                    [sty.dropdownLogo2openSelectbar]: hasVariant(
                      $state,
                      "openSelectbar",
                      "openSelectbar"
                    )
                  })}
                >
                  {renderPlasmicSlot({
                    defaultContents: (
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___4NMcf)}
                        displayHeight={"24px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"none"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"24px"}
                        loading={"lazy"}
                      />
                    ),

                    value: args.selectLogo3
                  })}
                </div>
                <div
                  data-plasmic-name={"dropdownLabel2"}
                  data-plasmic-override={overrides.dropdownLabel2}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.dropdownLabel2,
                    {
                      [sty.dropdownLabel2openSelectbar]: hasVariant(
                        $state,
                        "openSelectbar",
                        "openSelectbar"
                      )
                    }
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return currentItem;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
                {(() => {
                  try {
                    return $state.selectValue === currentItem;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return true;
                    }
                    throw e;
                  }
                })() ? (
                  <PlasmicImg__
                    data-plasmic-name={"checkedOptionSvg2"}
                    data-plasmic-override={overrides.checkedOptionSvg2}
                    alt={""}
                    className={classNames(sty.checkedOptionSvg2)}
                    displayHeight={"20px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"20px"}
                    loading={"lazy"}
                    src={{
                      src: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMCAyMCI+CiAgPHBhdGggZGF0YS1uYW1lPSJSZWN0YW5nbGUgMjA3IiBkPSJNMCAwaDIwdjIwSDB6IiBmaWxsPSJ0cmFuc3BhcmVudCIvPgogIDxwYXRoIGRhdGEtbmFtZT0iUGF0aCA3MCIgZD0iTTcuNTU0IDEzLjk0Nkw0LjMxMSAxMC43QTEuMDUzIDEuMDUzIDAgMDE0IDkuOTVhMS4wNTEgMS4wNTEgMCAwMS4zMTEtLjc1IDEuMDQ4IDEuMDQ4IDAgMDEuNzUtLjMxMSAxLjA1MiAxLjA1MiAwIDAxLjc1LjMxMUw4LjMgMTEuN2w2LjM4NS02LjM4NWExLjA1MyAxLjA1MyAwIDAxLjc1MS0uMzEyIDEuMDUzIDEuMDUzIDAgMDEuNzUuMzEyIDEuMDU1IDEuMDU1IDAgMDEuMzEuNzUgMS4wNTcgMS4wNTcgMCAwMS0uMzEuNzVMOS4wNSAxMy45NWExLjA1MiAxLjA1MiAwIDAxLS43NS4zMTEgMS4wNTQgMS4wNTQgMCAwMS0uNzQ2LS4zMTV6IiBmaWxsPSJyZ2JhKDI1Miw4Nyw1OSwuNSkiLz4KPC9zdmc+Cg==",
                      fullWidth: 20,
                      fullHeight: 20,
                      aspectRatio: 1
                    }}
                  />
                ) : null}
              </div>
              {(() => {
                try {
                  return $props.optionsLoop.length - 1 !== currentIndex;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return true;
                  }
                  throw e;
                }
              })() ? (
                <div
                  data-plasmic-name={"dividerWrapper"}
                  data-plasmic-override={overrides.dividerWrapper}
                  className={classNames(projectcss.all, sty.dividerWrapper, {
                    [sty.dividerWrapperopenSelectbar]: hasVariant(
                      $state,
                      "openSelectbar",
                      "openSelectbar"
                    )
                  })}
                >
                  <div
                    data-plasmic-name={"divider"}
                    data-plasmic-override={overrides.divider}
                    className={classNames(projectcss.all, sty.divider, {
                      [sty.divideropenSelectbar]: hasVariant(
                        $state,
                        "openSelectbar",
                        "openSelectbar"
                      )
                    })}
                  />
                </div>
              ) : null}
            </Stack__>
          );
        })}
      </div>
      <Embed
        data-plasmic-name={"embedHtml"}
        data-plasmic-override={overrides.embedHtml}
        className={classNames("__wab_instance", sty.embedHtml)}
        code={
          "<style>\r\n\r\n  /* For Firefox */\r\n  .select-version-scroller {\r\n      scrollbar-width: thin; /* Thinner scrollbar */\r\n      scrollbar-color: #fc573b #FEF5F4; /* Thumb color and track color */\r\n  }\r\n</style>\r\n"
        }
      />
    </div>
  );
}

const PlasmicDescendants = {
  select: [
    "select",
    "selectDropdown",
    "dropdownContent",
    "dropdownLogo",
    "dropdownLabel",
    "dropDownArrow",
    "optionsUl",
    "optionLi",
    "dropdownContent2",
    "dropdownLogo2",
    "dropdownLabel2",
    "checkedOptionSvg2",
    "dividerWrapper",
    "divider",
    "embedHtml"
  ],

  selectDropdown: [
    "selectDropdown",
    "dropdownContent",
    "dropdownLogo",
    "dropdownLabel",
    "dropDownArrow"
  ],

  dropdownContent: [
    "dropdownContent",
    "dropdownLogo",
    "dropdownLabel",
    "dropDownArrow"
  ],

  dropdownLogo: ["dropdownLogo"],
  dropdownLabel: ["dropdownLabel"],
  dropDownArrow: ["dropDownArrow"],
  optionsUl: [
    "optionsUl",
    "optionLi",
    "dropdownContent2",
    "dropdownLogo2",
    "dropdownLabel2",
    "checkedOptionSvg2",
    "dividerWrapper",
    "divider"
  ],

  optionLi: [
    "optionLi",
    "dropdownContent2",
    "dropdownLogo2",
    "dropdownLabel2",
    "checkedOptionSvg2",
    "dividerWrapper",
    "divider"
  ],

  dropdownContent2: [
    "dropdownContent2",
    "dropdownLogo2",
    "dropdownLabel2",
    "checkedOptionSvg2"
  ],

  dropdownLogo2: ["dropdownLogo2"],
  dropdownLabel2: ["dropdownLabel2"],
  checkedOptionSvg2: ["checkedOptionSvg2"],
  dividerWrapper: ["dividerWrapper", "divider"],
  divider: ["divider"],
  embedHtml: ["embedHtml"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCustomSelector__ArgProps,
          internalVariantPropNames: PlasmicCustomSelector__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCustomSelector__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "select") {
    func.displayName = "PlasmicCustomSelector";
  } else {
    func.displayName = `PlasmicCustomSelector.${nodeName}`;
  }
  return func;
}

export const PlasmicCustomSelector = Object.assign(
  // Top-level PlasmicCustomSelector renders the root element
  makeNodeComponent("select"),
  {
    // Helper components rendering sub-elements
    selectDropdown: makeNodeComponent("selectDropdown"),
    dropdownContent: makeNodeComponent("dropdownContent"),
    dropdownLogo: makeNodeComponent("dropdownLogo"),
    dropdownLabel: makeNodeComponent("dropdownLabel"),
    dropDownArrow: makeNodeComponent("dropDownArrow"),
    optionsUl: makeNodeComponent("optionsUl"),
    optionLi: makeNodeComponent("optionLi"),
    dropdownContent2: makeNodeComponent("dropdownContent2"),
    dropdownLogo2: makeNodeComponent("dropdownLogo2"),
    dropdownLabel2: makeNodeComponent("dropdownLabel2"),
    checkedOptionSvg2: makeNodeComponent("checkedOptionSvg2"),
    dividerWrapper: makeNodeComponent("dividerWrapper"),
    divider: makeNodeComponent("divider"),
    embedHtml: makeNodeComponent("embedHtml"),
    // Metadata about props expected for PlasmicCustomSelector
    internalVariantProps: PlasmicCustomSelector__VariantProps,
    internalArgProps: PlasmicCustomSelector__ArgProps
  }
);

export default PlasmicCustomSelector;
/* prettier-ignore-end */
